version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - sqlite_data:/app/db_data
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-ghana-sims-key-2026-level7
      - DB_PATH=/app/db_data/db.sqlite3

volumes:
  sqlite_data:
